version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: realfreelancer-db
    environment:
      POSTGRES_DB: realfreelancer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - realfreelancer-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: realfreelancer-backend
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: jdbc:postgresql://postgres:5432/realfreelancer
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_DRIVER: org.postgresql.Driver
      JWT_SECRET: 8fa8f90911ec227d330d36a30d4eabdcec6de84fc2447e23999914e2bae22608
      SERVER_PORT: 8080
      SERVER_ADDRESS: 0.0.0.0
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - realfreelancer-network
    volumes:
      - ./backend:/app
      - /app/target

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: realfreelancer-frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - realfreelancer-network
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:

networks:
  realfreelancer-network:
    driver: bridge 